LTCatt/PCL2Help

网站/Minecraft Wiki.json
=> Update Minecraft Wiki.json

启动器/手动选择Java路径.json, 启动器/手动选择Java路径.xaml, 启动器/设置分配内存大小.xaml
=> 添加"手动选择Java路径"

Minecraft/资源包安装.json, Minecraft/资源包安装.xaml, 个性化/XAML 格式.xaml, 帮助/提交帮助 - Git.json, 帮助/提交帮助 - Git.xaml
=> 优化界面布局，新增部分 XAML 用法

Minecraft/数据包安装.json, Minecraft/数据包安装.xaml
=> 添加数据包(原版模组)安装帮助

启动器/备份设置.xaml
=> 为 备份设置.xaml 添加一条提醒

Minecraft/安装 Mod.xaml
更新 安装 Mod 帮助，替换不规范的图片，改进精简说明文字。
=> 更新 安装 Mod 帮助

启动器/指定登录方式.xaml, 启动器/设置 LittleSkin 的外置登录.json, 启动器/设置 LittleSkin 的外置登录.xaml
=> 添加“设置 LittleSkin 的外置登录”帮助

Minecraft/数据包安装.xaml, 数据包安装.xaml
再次提交
附上 jsdelivr CDN 国内加载速度:
[![4GL3CT.png](https://z3.ax1x.com/2021/09/20/4GL3CT.png)](https://imgtu.com/i/4GL3CT)
=> 更改数据包安装加载太慢的问题

启动器/设置 LittleSkin 的外置登录.xaml
=> Update 设置 LittleSkin 的外置登录.xaml

个性化/XAML 格式.xaml
*再发一次是因为在 #126 中龙猫没有看见发的回复，无意冒犯，抱歉……*
**这样可以防止某些人访问不到 GitHub**
> 不直接连接 GitHub 可能会导致文件不同步……换句话说 GItHub 上的更新了，但是镜像的没更新
jsdelivr 会自动同步 Github 上面的同步，只要 Github 上的这个文件改了，那 jsdelivr 链接也会同步的
[演示视频](https://cdn.jsdelivr.net/gh/zkitefly/myphoto/%E5%BD%95%E5%B1%8F_Navigator_20220327154438.mp4)
>而且现在 jsdelivr 备案掉了
>连接更是不稳定了(
虽然掉了，要是与 Github 比，那就顺畅的很，且 Github 链接时不时会抽风（总之比 Github 链接好了太多不是吗？）
=> Update XAML 格式.xaml GithubLink to jsdelivrLink

个性化/XAML 格式.xaml
再一次将链接修改一下
在 https://cdn.jsdelivr.net/gh/user/repo 的 repo （及仓库名）后尾添加 @latest
原因是在逛知乎的时候，突然看到说 https://cdn.jsdelivr.net/gh/user/repo 这种组合是不会自动更新的，得是 https://cdn.jsdelivr.net/gh/user/repo@latest 的链接才行 - -!
=> Update XAML 格式.xaml

个性化/XAML 格式.json, 个性化/XAML 格式.xaml
添加了对EventType为打开帮助的介绍以及对local:MyListItem的简介
=> 添加了对EventType为打开帮助的介绍以及对local:MyListItem的简介

Minecraft/新手教程.json, 百科/Minecraft Wiki.json
=> 更改fandom网站为biligame网站解决国内访问白屏的问题

帮助/提交帮助 - VSCode.xaml
=> Update 提交帮助 - VSCode.xaml

启动器/联机.xaml
=> 修改 LanServerProperties 支持的 Minecraft 版本号

Minecraft/设置分配内存大小.xaml
=> 修正图片，并更换图床

Minecraft/安装 Mod.json, Minecraft/安装 Mod.xaml, Minecraft/安装世界.json, Minecraft/安装世界.xaml
第一次改，可能会有问题（）
Quilt目前不支持内置了Fabric API的mod。
Fabric有些Mod内置了Fabric API，所以不需要Fabric API作为前置。
尽量把两条MyHint合并了，但还是有很多MyHint...
=> 修改“安装 Mod”和"安装世界“；扔到美化网站上美化了一下

个性化/XAML 格式.xaml
=> 更新 Xaml 语法帮助

Minecraft/安装 Mod.json, Minecraft/安装 Mod.xaml, Minecraft/整合包安装.json, Minecraft/整合包安装.xaml
- 我针对上述页面进行了**大篇幅的修改**，因此错误可能会很多，如果大家能帮我一起完善这个更改，真的非常感谢啦！
- 如果 Merge #286 ，则会与其冲突
- 在文字表述上添加了 Modrinth；
- 优化了部分表述，使其尽可能更加清晰、简洁、明了；
- 修改了绝大部分上述页面的图片（会有几个漏网之鱼，不过都是不影响正常阅读使用的了）；
- 重新制作 **安装 Mod** 页面的 **下载并安装 Mod（CurseForge）** 部分，以和 **整合包安装** 页面风格相统一并有效避免了使用了过多 local:MyHint。
=> 修改 安装 Mod 和 整合包安装 以匹配 2.5.0 及以上版本（Modrinth 支持）

Minecraft/安装 Mod.xaml
=> 删除 安装 Mod 页面中意外出现的一个字符

Minecraft/安装 Mod.xaml, Minecraft/整合包安装.xaml
=> 更新 安装 Mod 和 整合包安装 的表述和图片以适应 2.5.3 版本的更改

启动器/指定登录方式.xaml
=> 修复 限制登陆方式页面 图片 404 问题

Minecraft/加入服务器.xaml, 启动器/LittleSkin 外置登录使用教程.xaml
加了两个报错：`Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException` `此服务器未启用飞行`，来源于 PCL x9 群……
另外就是网站尽可能地不使用 GitHub，然后让语言看上去更加的……额……书面化（
Edit：216 行这个文案要不要改一改……实在想不出怎么写了
```xaml
<TextBlock Margin="0,0,0,4" LineHeight="17"
Text="原因：生存 / 冒险模式玩家长时间静止在空中。" /> 
<TextBlock Margin="0,0,0,4" LineHeight="17"
Text="解决方法：如果多次遇到该问题，可以联系服主启用飞行；也可以尝试关闭你的外挂……" /> 
```
=> 完善 加入服务器 页面 & 修复图片

Minecraft/安装 Mod.xaml, Minecraft/安装世界.xaml, Minecraft/安装光影.xaml, Minecraft/微软账号登录失败.xaml, Minecraft/数据包安装.xaml, Minecraft/整合包安装.xaml, Minecraft/资源包安装.xaml, README.md, 启动器/LittleSkin 外置登录使用教程.xaml, 启动器/Microsoft Defender 添加排除项.xaml, 启动器/指定登录方式.xaml, 启动器/角色皮肤导出.xaml, 帮助/提交帮助 - VSCode.xaml, 帮助/提交帮助 - 编写规范.xaml
`cdn.img.z0z0r4.top` -> `img.z0z0r4.top/local`
=> fix: image url

帮助/提交帮助 - Intellij Idea.json, 帮助/提交帮助 - Intellij Idea.xaml
=> Intellij Idea关于提交的帮助教程

Minecraft/安装 Mod.xaml, 启动器/Microsoft Defender 添加排除项.xaml
最近时间比较紧，十几分钟赶出来的，改动比较大，但能检查到的都检查到了，但疏漏估计还是有的，还请指出啦——！谢谢
- 于 xaml 文件开首处添加图片备份连接
- 将 MyCard 中的 “ - ” 统一修改为括号以保证页面整齐
- 重制 安装 Mod 加载器 部分，修改操作步骤图片以统一风格符合规范
- 重排版并修正措辞 下载并安装 Mod（Mod 文件）部分，修改操作步骤图片以统一风格符合规范
- 合并部分 MyHint，尽可能减少 MyHint 数量使得页面整洁
=> 规范化并优化 Mod 安装 页面

帮助/提交帮助 - VSCode.json, 帮助/提交帮助 - VSCode.xaml
=> 修改“提交帮助 - VSCode”界面的部分地方

Minecraft/资源包安装.xaml, 帮助/提交帮助 - Intellij Idea.json, 帮助/提交帮助 - Intellij Idea.xaml
增加JB系IDE使用教程并规范InteillJ IDEA软件大小写。
=> 修改使用IntelliJ IDEA编辑帮助库教程、规范化教程图片

Minecraft/安装光影.xaml, 帮助/提交帮助 - 编写规范.xaml, 帮助/提交帮助.xaml, 帮助/自定义帮助.xaml, 指南/整合包制作 - Public.xaml, 指南/整合包制作 - Snapshot.xaml
fix Hex-Dragon/PCL2#2917
我翻了一下，确认 `PaddingRight` 都删掉了
=> 修复新版本出现的未知成员问题

Minecraft/加入服务器.xaml, Minecraft/存档损坏.json, Minecraft/存档损坏.xaml, Minecraft/安装 Mod.xaml, Minecraft/安装世界.json, Minecraft/安装世界.xaml, Minecraft/数据包安装.xaml, Minecraft/整合包安装.xaml, Minecraft/资源包安装.json, Minecraft/资源包安装.xaml
主要针对安装世界、安装资源包、存档损坏解决方案页面进行规范化。
重写安装世界页面，去除安装资源包页面冗余表述，扩充存档损坏步骤图片并重排版该页面。
=> 规范化帮助库页面（安装世界、资源包安装、存档损坏）

Minecraft/加入服务器.xaml
检索式：`is:pr is:closed 禁人`
提前祝各位新年快乐 awa ！
=> 添加禁人塔造成的连接服务器问题

Minecraft/加入服务器.xaml, Minecraft/安装 Mod.xaml, Minecraft/安装世界.xaml, Minecraft/安装光影.xaml, Minecraft/数据包安装.xaml, Minecraft/整合包安装.xaml, Minecraft/资源包安装.xaml, 指南/整合包制作 - Public.xaml, 指南/整合包制作 - Snapshot.xaml
涉及页面：
- 整合包制作（Public&Snapshot）
- Mod 安装
- 整合包安装
- 光影安装
- 世界安装
- 数据包安装
- 资源包安装
- 加入服务器
只用注释括起来的是希望未来可以找到可供代替的链接
=> 移除全部 MCBBS 链接

Minecraft/数据包安装.xaml
https://github.com/LTCatt/PCL2Help/pull/350#issuecomment-1952526474
=> 删除意外出现的 Minecraft Maps 字样

帮助/提交帮助.xaml
=> Fix https://pcl2-help.gitee.io/ 处于 502 状态 #367

个性化/XAML 格式.xaml
https://github.com/Hex-Dragon/PCL2/issues/3266 ，在列表项基础教程那里改了一句话
=> 追加自 2.7.4 对 MyListItem 打开联网帮助项的说明

Minecraft/加入服务器.xaml
删掉无用的 `<TextBlock Margin="2,0,0,4" LineHeight="17"/>`
更改前：
更改后：
=> 更改 Card 大小

Minecraft/加入服务器.xaml, Minecraft/存档损坏.xaml, Minecraft/安装 Mod.xaml, Minecraft/安装世界.xaml, Minecraft/安装光影.xaml, Minecraft/微软账号登录失败.xaml, Minecraft/数据包安装.xaml, Minecraft/整合包安装.xaml, Minecraft/更新 Mod.xaml, Minecraft/资源包安装.xaml, 启动器/LittleSkin 外置登录使用教程.xaml, 启动器/Microsoft Defender 添加排除项.xaml, 启动器/指定登录方式.xaml, 启动器/角色皮肤导出.xaml, 帮助/提交帮助 - VSCode.xaml, 帮助/提交帮助 - 编写规范.xaml
close https://github.com/LTCatt/PCL2Help/issues/393
=> feat: FallbackSource applied

个性化/XAML 格式.xaml
一个~毫无意义的~小编辑
让其他主页作者知道有这个 Fallback 选项
藏在注释里不太直观
=> 增加 FallbackSource 属性解释

README.md
I've made some changes to the document, just minor ones, to make it look better.
=> docs: Modify something. Small contributions

个性化/XAML 格式.xaml
适配 https://github.com/Hex-Dragon/PCL2/pull/5849
=> docs(update XAML 格式):添加自定义事件 - 下载版本

个性化/XAML 格式.xaml
此地址目前在中国大陆地区可用且响应速度较快
Relate https://github.com/Meloong-Git/PCL/issues/6960
=> fix(docs): 更新地址
